/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],
    //未分类: 
    //新手教程
    

    "This Pokemon is marked as Special, and cannot receive shiny mutations through genetics!": "此宝可梦被标记为特殊宝可梦, 无法通过遗传获得闪光突变!",
    "While in combat, Pokemon get tired and lose a very small fraction of their hp yada yada.": "在战斗中, 宝可梦会感到疲劳, 并失去一小部分生命值。",
    
    //杂项
    "Move": "招式",
    "Split": "分类",
    "and": "和",
    "Auto-Refight is active!": "自动再战已激活！",
    "(Requires an": "(需要一个",
    "(Wont use": "(不会消耗",
    "(Wont consume an": "(不会消耗",
    "Auto-Refight Ticket)": "自动再战票)",
    "Auto-Refight Tickets)": "自动再战票)",
    "Click to disable it": "点击此处关闭",
    "Auto-Refight Tickets remaining)": "自动再战剩余次数)",
    "Pokemon": "宝可梦",
    "Z": " Z",
    "caught": "捕捉",
    "WIP": "暂无",
    "STAB": "本系加成",
    "Physical": "物理",
    "Special": "特殊",
    "A new update is available. Refresh to update.": "有新的更新可用。请刷新网页以更新。(汉化版请等待同步更新)",
    "Inflicts": "施加",
    "Flying-Type": "飞行属性",
    "Paralyzed": "麻痹",
    "enabled": "启用",
    "disabled": "禁用",
    "Go back": "返回",
    "Moves": "招式",
    "Remove": "移除",
    "Shiny Pokemon": "闪光宝可梦",
    "Tutorials:": "教程:",
    "Reward Received": "收到的奖励",
    "or": "或",
    "Refreshing the browser restores their health back to full": "刷新浏览器可将其运行状况恢复到满状态",
    "\n            Start\n": "\n            开始\n",
    "\n                    Abilities": "\n                    特性",
    //图标代码, 不能汉化
    //图标代码, 不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "▶": "▶",
    "◀": "◀",
    "???": "???",
    "✈": "✈",
    "★": "★",
    "★  ★": "★  ★",
    "★  ★  ★": "★  ★  ★",
    "· · · · · ·": "· · · · · ·",
    "· · · · ·": "· · · · ·",
    "· · · ·": "· · · ·",
    "· · ·": "· · ·",
    "· ·": "· ·",
    "·": "·",
    "★  ★  ★  ★": "★  ★  ★  ★",
    " Tm": " Tm",
    "✦": "✦",
    "✦✦✦✦": "✦✦✦✦",
    "✦✦✦✦✦": "✦✦✦✦✦",
    "★  ★  ★  ★  ★": "★  ★  ★  ★  ★",
    "SSS": "SSS",
    "SS": "SS",
    "✦✦✦": "✦✦✦",
    "✦✦": "✦✦",
    "★★": "★★",
    "★★★": "★★★",
    "★★★★": "★★★★",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",
    ".cls-1,.cls-2{fill:none;}.cls-2{stroke:currentcolor;stroke-linecap:round;stroke-linejoin:round;stroke-width:100px;}": "",
    "★  ★  ★  ★  ★  ★": "★  ★  ★  ★  ★  ★",
    "⬤": "⬤",
    "${returnDivisionLetter(returnPkmnDivision(poke))}": "",
    "EXP Training": "",
    "Expand Lore": "",
    //树游戏
    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏, 但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长, 则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长, 则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化, 不完整',
    'LAST, AUTO, INCOMPLETE': '最后, 自动, 不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    "\n\n\n            AFK time is being calculated, please wait...\n": "\n\n\n            正在计算挂机时间, 请稍候...\n",
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    //导航栏
    "Travel": "旅行",
    "VS": "对战",
    "Items": "物品",
    "Team": "队伍",
    "Dex": "图鉴",
    "Poke-Mart": "友好商店",
    "Training": "训练",
    "Genetics": "遗传",
    "Export Reward": "导出奖励",
    "Wonder Trade": "奇迹交换",
    "Dictionary": "百科",
    "Guide": "游戏指南",
    'Settings': '设置',
    "Full Screen": "全屏",
    //设置菜单
    "Export Data": "导出存档",
    "Import Data": "导入存档",
    "Data to Text": "以文本形式处理存档",
    "This is your savefile code": "这是你的存档代码",
    "You can copy or paste savefile codes here to export or import saves": "你可以在此处复制或粘贴存档代码以导出或导入存档",
    "Copy": "复制",
    "Paste": "粘贴",
    "Load": "加载",
    "Theme": "主题",
    "onyx": "缟玛瑙",
    "lilac": "紫丁香",
    "verdant": "翠绿",
    "cherry": "樱桃",
    "coral": "珊瑚",
    "oled": "纯黑",
    "spooky": "幽灵",
    "Cherry Theme": "樱桃主题",
    "Coral Theme": "珊瑚主题",
    "Dark Theme": "暗黑主题",
    "Light Theme": "明亮主题",
    "Lilac Theme": "淡紫主题",
    "Oled Theme": "纯黑主题",
    "Onyx Theme": "玛瑙主题",
    "Verdant Theme": "翠绿主题",
    "Hide non-new Pokemon got in summary:": "隐藏摘要中出现的非新宝可梦: ",
    "Sustract 1 to current Wild Area rotation:": "当前旷野地带的轮换周期减1: ",
    "Game modifiers": "游戏模式修改器",
    "Game Modifiers": "游戏模式修改器",
    "Challenges": "挑战",
    "Nuzloke Mode": "限制模式",
    "If any of your Pokemon get defeated while battling a trainer of VS Trainers, it will permanently be unusuable until you turn this mode off": "在对战训练家的战斗中, 若任何宝可梦被击败, 它将永久无法使用, 直至关闭此模式",
    "Hard Mode": "困难模式",
    "Trainers have twice the health. Only applies to VS Trainers": "训练家的宝可梦生命值变为两倍(仅适用于对战训练家)",
    "Cheats": "作弊",
    "No IVs": "满个体值(IV)",
    "All of your Pokemon have functionally max IVs regardless of their actual IVs. This can be toggled off without any permanent changes": "所有宝可梦的个体值(IVs)均视为满值, 与实际个体值无关。此效果可随时关闭, 且不会造成永久性改动",
    "Longer AFK": "更长的挂机时间",
    "Fatigue damage is reduced by x3": "疲劳伤害降低至原本的1/3",
    "There are no side-effects to this modifier": "此修改无任何副作用",
    "ENABLED": "启用",
    "DISABLED": "禁用",
    "Credits": "鸣谢",
    "Wipe Data": "清空数据",
    //游戏指南
    "Game Guide": "游戏指南",
    "Game Guide\n": "游戏指南\n",
    //检查
    "Inspecting": "检查",
    "Some elements that can be inspected include areas, trainers, moves, status effects, wild pokemon, team pokemon and items": "可以检查的元素包括区域、训练师、招式、异常状态、野生宝可梦、队伍宝可梦和道具",
    "Right click/long press on most elements can give further information. You can further right click/long press on information within information.": "对大部分功能项右键点击/长按, 可查看详细说明。你还可对说明内的次级信息再次右键点击/长按, 查看更多内容。",
    //战斗: 能力值
    "Stats": "能力值",
    "Health": "生命",
    "Attack": "攻击",
    "Defense": "防御",
    "Speed": "速度",
    "Special Attack": "特攻",
    "Special Defense": "特防",
    "ATK": "攻击",
    "SDEF": "特防",
    "SATK": "特攻",
    "SPE": "速度",
    "Each species of Pokémon share the same base stats that determine the actual stats of a Pokémon at a given level": "每个种类的宝可梦共享相同的种族值, 这些数值决定了宝可梦在特定等级时的实际能力值",
    "Stats determine how much damage they deal and receive (see Battle: Moves). The speed stat determines how fast a Pokemon executes a move": "各项能力值决定了宝可梦造成和承受伤害的多少(详见战斗: 招式)。速度决定了宝可梦执行招式的速度",
    "Individual Values, or IV's, multiply base stats, and can be increased by getting multiple copies of Pokemon": "个体值(IV)会增强能力值, 并且可以通过获得多个相同的宝可梦个体来提高",
    "Depending on their base stats, a Division will be asigned to them. You might use this Division letter to quickly assess which Pokemon can perform better on the short term": "根据它们的种族值, 会为其分配一个评级。你可以利用这个评级来快速判断哪些宝可梦在短期内表现更佳",
    //战斗: 特性
    "Abilities": "特性",
    "ability": "特性",
    "Abilities are traits that a Pokemon can have. While they are randomised, some abilities can only appear on specific typings. Abilities are sorted in three categories; common, uncommon and rare": "特性是宝可梦可以拥有的特质。它们虽然是随机的, 但某些特性只会在特定的属性上出现。特性分为三类: 常见、罕见和稀有",
    "Hidden abilities are innate species-dependant traits that need to be unlocked with an Ability Capsule. Once unlocked, their effect will permanently be active alongside their other ability. Same Hidden Ability and Ability wont stack with eachother": "隐藏特性是依赖于物种的先天特质, 需要用特性胶囊解锁。一旦解锁, 它们的效果将永久生效, 并与宝可梦的其他特性共同存在。相同的隐藏特性和特性不会相互叠加",
    //战斗: 经验值
    "Pokemon gain experience by defeating foes, and share a portion of it among the team. This will also be the case even if the team Pokemon are defeated": "宝可梦通过击败对手获得经验, 并会在队伍中分享一部分。即使队伍中的宝可梦被击败, 此规则同样适用",
    "Experience gain is proportional to the level difference. A level difference of +-5 levels will net the same amount, while more than 5 levels of difference will greatly increase the amount received.": "经验值获取量与等级差成正比。等级差在 ±5 级以内将获得相同数量, 而超过5级的等级差会大幅增加获得的经验值",
    "A Pokemon 10 levels higher will not yield any experience": "超过对手 10 级的宝可梦不会获得任何经验",
    //战斗: 招式
    "This is a Signature Move. Signature moves will automatically be learnt at level 100": "这是一个招牌招式。招牌招式将在100级时自动学会",
    "This is an Egg Move. Egg moves can be learnt with genetics, using a sample that knows said move, at regular move transfer odds": "这是一个蛋招式。蛋招式可以通过遗传学习。请使用一个已学会该招式的宝可梦作为样本, 且按照常规招式遗传几率进行遗传。",
    "Some Pokemon might have Signature Moves. Signature Moves are species-dependant moves that a Pokemon learn at level 100. Signature Moves can't be inherited through genetics, unless the host has the corresponding Egg Move": "有些宝可梦可能拥有专属技能, 这是特定物种的宝可梦在100级时学习的技能。专属技能无法通过遗传继承, 除非该宝可梦拥有对应的蛋招式。",
    "Moves are learnt every 7 levels. Moves can be switched by right click/long press on a team pokemon": "每 7 级学习一次招式。招式可以通过 右键/长按 队伍宝可梦切换",
    "Damaging moves are divided into physical and special moves": "伤害型招式分为物理招式和特殊招式",
    "The category of the move determines whether the move's damage depends on the user's Attack or Special Attack stat and the target's Defense or Special Defense": "招式的类别决定了招式的伤害是否取决于使用者的攻击或特攻属性, 以及目标的防御或特殊防御",
    "Some Pokemon might have Signature Moves. Signature Moves are species-dependant moves that a Pokemon learn at level 100. Signature Moves can't be inherited through genetics": "有些宝可梦可能有招牌招式。招牌招式是宝可梦在100级时学习的与物种相关的招式。招牌招式不能通过基因遗传",
    "Some moves might be restricted. Only one restricted move might be equipped at a time on the active Pokemon": "部分招式为限定招式, 出战宝可梦同一时间仅可装备一个限定招式",
    //战斗: 本系加成
    "If a Pokemon uses a damaging move that has the same type as one of that Pokemon's types, the move's damage is increased by x1.5": "如果宝可梦使用了与自己属性相同的伤害招式, 该招式的伤害将提高 1.5 倍",
    "This is known as same-type attack bonus, or STAB": "这就是所谓的本系加成(STAB)",
    "Furthermore, Pokemon with a single typing will receive +0.2 extra STAB damage": "此外, 单一属性的宝可梦将额外获得 0.2 倍本系招式伤害加成",
    //战斗: 交叉之力
    "Cross-Power": "交叉之力",
    "If a Pokemon uses a damaging move that is preceded (immediately or not) by a damaging move of a different type of the executed move, it will receive a 1.3x damage multiplier. This is indicated with a cross pattern on the move bar of the affected move": "如果宝可梦使用的伤害型招式之前(无论是否紧接着)有一个与它属性不同的伤害型招式, 该招式会获得 1.3 倍伤害加成。这会在受影响招式的招式条上以交叉图案显示",
    //战斗: 战斗疲劳
    "Battle Fatigue": "战斗疲劳",
    "Pokemon lose a very small fraction of their maximum health when attacking. This damage can be mitigated by a sum of the HP, Defense and Special Defense of the Pokemon, meaning bulkier Pokemon can battle for longer": "宝可梦攻击时会损失一小部分最大生命值。这个伤害可以通过宝可梦的HP、防御和特防的总和来减轻, 这意味着耐久更高的宝可梦可以战斗更长时间",
    //战斗: 异常状态
    "Status Effects": "异常状态",
    "Paralysis": "麻痹",
    "Burn": "灼伤",
    "Freeze": "冰冻",
    "Poisoned": "中毒",
    "Sleep": "睡眠",
    "Confused": "混乱",
    "BRN": "灼伤",
    "FRZ": "冰冻",
    "ZZZ": "睡眠",
    "PSN": "中毒",
    "PAR": "麻痹",
    "CNF": "混乱",
    "25% chance for moves to fail to deal damage and Speed is reduced by 75%": "招式有 25% 的概率无法造成伤害, 且速度降低 75%",
    "50% chance for moves to fail to deal damage": "招式有 50% 的概率无法造成伤害",
    "Decreases Physical Attack by 50% and deals damage every turn": "攻击降低 50%, 且宝可梦每回合受到伤害",
    "Decreases Special Attack by 50% and deals damage every turn": "特攻降低 50%, 且宝可梦每回合受到伤害",
    "Moves fail to deal damage": "招式无法造成伤害",
    "Certain moves inflict Status Effects such as": "某些招式会造成异常状态, 例如",
    "Certain moves inflict status effects, such as": "某些招式会造成异常状态, 例如",
    "Status Effects, like temporal stat changes, will count down with turns. You can only apply one Status Effect at a time": "异常状态, 如同临时能力变化一样, 持续时间会随回合数递减。一次只能施加一个异常状态",
    "You can further check their effects by right click/long press": "你可以通过 右键单击/长按 来进一步查看它们的效果",
    //战斗:能力提高与能力降低
    "Buffs and Debuffs": "能力提高与能力降低",
    "Buffs and debuffs of the same magnitude will not stack with each other (IE x2 50% Attack Up), but different ones will (50% + 100% Attack Up)": "同种幅度的能力提高或降低效果不会相互叠加(例如两次+50%攻击力)，但不同幅度的效果可以叠加(例如+50%与+100%攻击力)",
    "Like status effects, increases or decreases of stats last for 3 turns by default (Except Speed decreases, which last 2)": "与异常状态类似, 能力提高或降低的效果默认持续3回合(但速度降低除外,仅持续2回合)",
    //战斗: 天气
    "Trick Room": "戏法空间",
    "Slower Pokemon become faster, faster Pokemon become slower. Additionally, multiplies the damage based on how slow the Pokemon originally was by x1.0 to x1.5": "速度较慢的宝可梦会变快, 速度较快的宝可梦会变慢。此外, 基于宝可梦原本的速度慢速程度, 造成的伤害会提高 1-1.5 倍。",
    "Weird Room": "怪异房间",
    "Decrease the attack and defense of all active Pokemon by 3 stars": "使场上所有宝可梦的攻击与防御降低3星",
    "Cross Room": "交叉领域",
    "Increases the damage dealt by cross-power by 25%": "使 交叉之力 伤害加成提高 25%",
    "Light Screen": "光墙",
    "Super-effective damage dealt to your team is reduced to neutral": "对己方队伍造成的效果拔群的伤害将减弱为一般伤害",
    "Safeguard": "神秘守护",
    "Protects your team from status effects and stat reductions": "保护己方队伍免受异常状态与能力降低的影响",
    "Certain moves can change the weather to altered ones such as": "某些招式可以改变天气, 例如",
    "Altered weathers will last for 15 turns, and only can be changed after 30": "改变的天气将持续15个回合, 只有在30回合后才能改变",
    //闪光宝可梦
    "At a rate of 1/400, Pokemon can be shiny. These odds can be boosted through different means": "有1/400的概率, 宝可梦可以发光。这些可能性可以通过不同的方式来提高",
    "Shiny Pokemon deal 15% more damage. The visual distinction can be toggled from their move menu. This wont affect the damage bonus they get": "闪光的宝可梦造成的伤害提高 15%。视觉上的区别可以通过招式菜单切换。这不会影响他们得到的伤害加成",
    "Shiny Pokemon do not carry over their evolutions. Instead, genetics must be used": "闪光宝可梦的进化形态不会继承闪光状态。相反, 必须通过遗传系统来获得闪光进化形态。",
    //遗传学: 快速指南
    "Quick Guide": "快速指南",
    "Genetics allows you to modify a Pokemon beyond what is considered normal for the species, here is a quick overview of what you can achieve with operations:": "遗传系统可让你对宝可梦进行超越其物种常规设定的改造, 以下为你简要介绍各类培育操作可实现的效果: ",
    "Shiny Mutation: You can inherit the shiny mutation, with a 100% chance, to members of the same family. You can also attempt to spread a new shiny mutation by using a shiny sample": "闪光变异: 向同谱系的宝可梦遗传闪光变异时, 成功率为100%；也可使用闪光宝可梦作为样本, 尝试培育出新的闪光变异个体",
    "IV Boosting: Simply by doing any operation, regardless of the compatibility, the IV's of the host will attempt to increase. Useful for Pokemon with little to no IV's": "个体值提高: 只需执行任意培育操作, 无论兼容性如何, 主体宝可梦的个体值都将有概率提高, 该功能适用于个体值极低或无个体值的宝可梦",
    "IV Inheriting: An advanced alternative to the previous. You can inherit IV's from a species to another depending on factors such as compatibility or genetic-aiding items used": "个体值遗传: 作为个体值提高的进阶替代方案, 你可根据兼容性、所使用的遗传辅助道具等因素, 将一个物种的个体值遗传给另一个物种",
    "Move Relearn: When completing an operation, all but the four selected moves of the host will be reset, meaning you can attempt to get stronger moves with each operation": "招式重学: 完成培育操作后, 主体宝可梦除已选定的四个招式外, 其余招式均会重置, 这意味着你可通过每次培育操作尝试习得更强的招式",
    "Move Inheriting: An advanced alternative to the previous, you can inherit moves from the sample that would otherwise not be available to you through learning": "招式遗传: 作为个体值遗传的进阶拓展方案, 你可从样本宝可梦处, 遗传到常规学习方式无法掌握的招式",
    "Ability Inheriting: Using a Destiny Knot, you can swap abilities with the sample, getting access to otherwise-impossible combinations": "特性遗传: 使用 红线 可与样本宝可梦互换特性, 从而获得常规方式无法实现的特性组合",
    //遗传学: 兼容性
    "Compatibility determines how similar the sample is to the host. This influences various parameters such as the chances of inherit, or shiny mutations (only if the sample is shiny)": "兼容性决定了样本与宿主的相似程度。这会影响各种参数, 如遗传的机会, 或闪光的突变（仅当样本是闪光的）",
    "Sharing one type with the sample will yield one level of compatibility, whereas sharing two types will increase it by two levels.": "宿主与样本同一个属性将获得 1级 兼容性, 而2个属性相同将获得 2级 兼容性",
    "Additionally, if the sample is of the same evolutive line as the host, it will recieve maximum compatibility": "此外, 如果样本与宿主具有相同的进化系, 它将获得最大的兼容性(3级)",
    //遗传学: 能量消耗
    "Power cost determines how taxing it is to modify the host. This influences the time to complete the operation": "能量消耗决定了修改宿主的成本。这会影响完成操作的时间",
    "This is determined by the division of the host. A higher division will exponentially increase the time required to modify the Pokemon": "这是由宿主的评级决定的。更高的评级将增加修改宝可梦所需的时间",
    //奇迹交换
    "Dialga!": "帝牙卢卡!",
    "Every 12h you might receive a random pokemon": "每12小时你能收到一只随机的宝可梦",
    "Let's do it!": "开始吧!",
    //遗传
    "With genetics, you can modify the parameters of a level 100 Pokemon (the host) and influence them based on another Pokemon (the sample)": "借助遗传功能, 你可对100级的宝可梦(宿主)调整各项参数, 并以另一只宝可梦(样本)为蓝本对其进行改造。",
    "Doing so, the level of the host will reset back to 1 while keeping all 4 of its currently selected moves, and a chance to increase its IV's": "执行该操作后, 宿主宝可梦的等级将重置为1级, 同时保留其当前选定的4个招式, 并有概率提高自身的个体值。",
    "Genetics can also be influenced by using genetic-aiding items, which you can use at the end of the operation": "你也可在操作结束阶段使用遗传辅助道具, 为遗传的效果提供加成。",
    "You can find more information about the specifics of genetics in the guide section": "你可在指南板块中查看宝可梦遗传机制的详细说明",
    "Warning, high Power Cost! Only 5 out of 6 maximum IV's per stat will be inherited!": "警告! 能量消耗高! 每项个体值最多只能遗传5级 (共6级) !",
    "Warning, power cost too high! Only 5 out of 6 maximum IV's per stat will be inherited!": "警告! 能量消耗很高! 每项个体值最多只能遗传5级 (共6级) !", //不存在的文本??
    "Warning, very high Power Cost! Only 4 out of 6 maximum IV's per stat will be inherited!": "警告：能量消耗极高! 每项个体值最多只能遗传4级 (共6级) !",
    "Select a host Pokemon": "选择宿主宝可梦",
    "Select a sample Pokemon": "选择样本宝可梦",
    "Compatibility": "兼容性",
    "Power Cost": "能量消耗",
    "Time to complete operation": "完成遗传所需时间",
    "% for shiny mutation": "闪光突变概率",
    "% to inherit a move from the sample": "遗传一个样本招式概率",
    "% to inherit sample's Speed Iv's": "遗传样本的 速度 个体值 的概率",
    "% to inherit sample's S. Defense Iv's": "遗传样本的 特防 个体值的概率",
    "% to inherit sample's S. Attack Iv's": "遗传样本的 特攻 个体值的概率",
    "% to inherit sample's HP Iv's": "遗传样本的 生命 个体值的概率",
    "% to inherit sample's Attack Iv's": "遗传样本的 攻击 个体值的概率",
    "% to inherit sample's Defense Iv's": "遗传样本的 防御 个体值的概率",
    "Pokerus detected on the host! Genetic compatibility is increased by one level!": "检测到宿主感染宝可梦病毒! 遗传兼容性提高 1 级!",
    "Are you sure you want to abort the operation?": "你确定要中止操作吗？",
    "Nothing but time will be lost": "除了时间之外不会有任何损失",
    "Operation overview": "遗传结果",
    "✦ Shiny Mutation!": "✦ 闪光突变!",
    "★ Ability swapped!": "★ 特性交换!",
    "◆ Attack Iv's increased!": "◆ 攻击个体值提高!",
    "◆ Speed Iv's increased!": "◆ 速度个体值提高!",
    "◆ Defense Iv's increased!": "◆ 防御个体值提高!",
    "◆ HP Iv's increased!": "◆ HP个体值提高!",
    "◆ Special Attack Iv's increased!": "◆ 特攻个体值提高!",
    "◆ Special Defense Iv's increased!": "◆ 特防个体值提高!",
    "❖ Attack Iv's inherited!": "❖ 攻击个体值遗传!",
    "❖ Speed Iv's inherited!": "❖ 速度个体值遗传!",
    "❖ Defense Iv's inherited!": "❖ 防御个体值遗传!",
    "❖ HP Iv's inherited!": "❖ HP个体值遗传!",
    "❖ Special Attack Iv's inherited!": "❖ 特攻个体值遗传!",
    "❖ Special Defense Iv's inherited!": "❖ 特防个体值遗传!",
    //宝可梦病毒
    "Pokerus": "宝可梦病毒",
    "PKRS": "病毒",
    "Every 12 hours, some of your Pokemon will contract Pokerus. This virus is entirely beneficial, and will add one level of compatibility to the Pokemon in genetics when used as a host": "每12小时, 你的部分宝可梦会感染宝可梦病毒。这种病毒完全有益。当此宝可梦作为宿主时, 会提高 1 级遗传兼容性。",
    //训练
    "Challenge your Pokemon against waves of foes in order to get stronger. You will naturally have typing advantage against Pokemon fought against, and their level will scale to yours. Type Immunities inside training will be instead converted to resistances.": "让你的宝可梦迎战一波波对手, 锤炼自身变得更强。在训练中, 你会对战被你属性克制的对手, 对手的等级也会随你的宝可梦等级同步调整。训练模式内的属性免疫效果, 将转化为属性抗性。",
    "Failing a training will result in no gains": "失败的训练不会有任何收获",
    "Select a Pokemon to train": "选择一个宝可梦进行训练",
    "Level Training": "等级训练",
    "Re-rolls the ability of a Pokemon": "重置一只宝可梦的特性",
    "IV Training": "个体值训练",
    "Ability Training": "特性训练",
    "Hidden Ability Training": "隐藏特性训练",
    "Move Training": "招式训练",
    "Try to improve your Pokemon further:": "尝试让你的宝可梦变得更强: ",
    "Get better type-matching moves": "获得更好的属性匹配招式",
    "Get better moves that correctly match your stat distribution (Physical/Special)": "获得更匹配你能力值分配的招式（物理/特殊）",
    "Use Stat Up moves that match your moves": "使用与你的招式相匹配的能力提高类招式",
    "Unlock a Hidden Ability": "解锁隐藏特性",
    "Get a better Ability": "获得更好的特性",
    "Modify stats with Genetics": "通过遗传系统调整能力值",
    "Training Failed :(": "训练失败 :(",
    "Fully max a Pokemon's level. Can only be done with less than Level 100": "将宝可梦提高至满级, 仅可对等级未满 100 级的宝可梦使用",
    "Learn a new Pokemon Move. Can only be done with less than 20 moves, or when a new move is available": "让宝可梦学会一个新技能, 仅可对已学习技能未满 20 个或有可学新技能的宝可梦使用",
    "Rerolls the Pokemon Ability": "重新随机宝可梦的特性",
    //友好商店
    "Poke-Mart\n": "友好商店\n",
    "Goods": "商品",
    "You cant afford to purchase this": "你还买不起这个物品",
    "Cant Afford": "还买不起哦",
    "How many will you buy?": "你想购买多少个?",
    "Available decor will rotate in": "在售装饰物将轮换于",
    "Available items will rotate in": "在售物品将轮换于",
    //道具
    "Held": "携带物",
    "TM's": "技能机",
    "Key": "贵重物",
    "Evo": "进化",
    "Memo": "记忆",
    "Limited": "限量物品",
    "Decor": "装饰物",
    "Gems": "宝石",
    "Berry": "树果",
    "Exchange": "交换物品",
    //图鉴
    "Give it a nickname!": "取个名字吧!",
    "Remove decor": "移除装饰物",
    "Filters": "过滤器",
    "evolution": "进化",
    "Evolution": "进化",
    "not evolved (all)": "未进化 (全部)",
    "not evolved (level)": "未进化 (等级)",
    "locked HA": "锁定隐藏特性",
    "shiny": "闪光",
    "not shiny": "非闪光",
    "ribbon": "缎带",
    "has ribbon": "有缎带",
    "signature": "招牌技",
    "has signature": "有招牌技",
    "has egg move": "有蛋招式",
    "tag": "标签",
    "Tag:": "标签:",
    "none": "无",
    "None": "无",
    "red": "红",
    "orange": "橙",
    "yellow": "黄",
    "green": "绿",
    "lime": "青",
    "teal": "蓝绿",
    "blue": "蓝",
    "pink": "粉",
    "magenta": "品红",
    "hidden": "隐藏",
    "sort": "排序",
    "atk Total": "攻击",
    "def Total": "防御",
    "hp Total": "生命",
    "satk Total": "特攻",
    "sdef Total": "特防",
    "spe Total": "速度",
    "atk BST": "攻击种族值",
    "spe BST": "速度种族值",
    "satk BST": "特攻种族值",
    "def BST": "防御种族值",
    "sdef BST": "特防种族值",
    "hp BST": "生命种族值",
    "atk IV's": "攻击个体值",
    "satk IV's": "特攻个体值",
    "spe IV's": "速度个体值",
    "def IV's": "防御个体值",
    "sdef IV's": "特防个体值",
    "hp IV's": "生命个体值",
    "Clear Filters": "清空过滤",
    "Keywords": "关键词",
    "Operators:": "搜索技巧: ",
    "![keyword]: Exclude from search": "![关键词]: 从搜索中排除",
    "[keywordA] or [keywordB]: Search keywordA OR keywordB": "[关键词A] 或 [关键词B]: 搜索关键词A或关键词B",
    "[keywordA] [keywordB]: Search for keywordA AND keywordB": "[关键词A] [关键词B]: 搜索同时包含关键词A和关键词B",
    "Keywords:": "关键词列表: ",
    "Pokemon keywords:": "宝可梦关键词: ",
    "Move keywords:": "招式关键词: ",
    //队伍
    "Select a Pokemon to add to the team": "选择一只宝可梦加入队伍",
    "Edit team name": "编辑队伍名称",
    "Select your preference for the team (Your current team will be replaced by it)": "选择您偏好的队伍（您当前的队伍将被替换）",
    "Left = Defensive, Right = Offensive": "左 = 防守, 右 = 进攻",
    "Team Auto-Build": "队伍自动构建",
    "Auto-Build": "自动构建",
    "Copy Team": "复制队伍",
    "Select the target team slot to overwrite": "选择要覆盖的目标队伍的位置",
    "Duplicate Team": "复制队伍（生成副本）",
    //对战
    "\n                Trainers": "\n                训练家",
    "Trainers": "训练家",
    "VS Trainers": "与训练家对战",
    "Defeat increasingly difficult trainers and carve yourself a path of fame! You may unlock additional areas to explore as your progress": "击败越来越强的训练家, 闯出自己的成名之路！随着不断进步, 你还将解锁更多可供探索的区域",
    "Battle Frontier": "对战开拓区",
    "All trainers defeated!": "已击败所有训练家！",
    "How about the Battle Frontier?": "要不要去对战开拓区试试？",
    "+ Field Effect": "+ 场地效果",
    "Field Effect": "场地效果",
    "Field Effects": "场地效果",
    "New features unlocked!": "新功能已解锁！",
    "Export Reward unlocked": "导出奖励 已解锁",
    "Mystery Gift unlocked": "神秘礼物 已解锁",
    "New Dungeon: Sinnoh Underground": "新迷宫: 神奥地下通道",
    "New Dungeon: Beginner Dojo": "新迷宫: 初级道场",
    "New Dungeon: Advanced  Dojo": "新迷宫: 进阶道场",
    "New Dungeon: Exper Dojo": "新迷宫: 专家道场",
    "New Dungeon: Victory Road": "新迷宫: 冠军之路",
    "New Dungeon: Glistering Cave": "新迷宫: 光辉洞穴",
    "New Wild Area unlocked": "新旷野地带 已解锁",
    "Poke-Mart unlocked": "友好商店 已解锁",
    "Apricorn exchange in the Poke-Mart is now available!": "友好商店的球果交换现已开放!",
    
    //对战开拓区
    "VS Frontier": "对战开拓区",
    "Little Cup": "小小联盟",
    "Great League": "超级联盟",
    "Ultra League": "究极联盟",
    "Master League": "大师联盟",
    "Trainer Reset": "训练家重置",
    "Battle Factory": "对战工厂",
    "Battle Tower": "对战塔",
    "Battle Arena": "对战竞技场",
    "Reach a minimum score of 1000 in order to get rewards": "达到最低分数 1000 以获得奖励",
    "All trainers defeated for now": "目前所有训练家已击败",
    "Pick a difficulty for the next trainer": "为下一位训练家选择难度",
    "(Right click/long tap to see the field effect details)": "（右键单击/长按查看场地效果详情）",
    "division and below only": "仅限该评级及以下",
    "Every time you enter the factory, your score will reset, but you can try as many times as you'd like": "每次进入对战工厂, 你的分数都会重置, 但你可不限次数挑战",
    "Every time you enter the tower, you will start from floor 1, but you can try as many times as you'd like": "每次进入对战塔, 你都将从第 1 层开始挑战, 但你可不限次数挑战",
    "Factory Pokemon": "对战工厂宝可梦",
    "The Battle Factory is a challenge in which your goal is to deal the maximum amount of damage. Every turn you will take a fixed amount of damage, and damage from status effects is disabled.": "对战工厂是一项以打出最高伤害为目标的挑战。每回合你会受到固定数值的伤害, 且异常状态造成的伤害将被屏蔽",
    "The Battle Frontier houses different types of challenges under a specific division restriction that rotates every three days. Trainers fought here will reset every day": "对战开拓区开放多种挑战模式, 挑战受特定组别限制且该限制每 3 天轮换一次。在此遭遇的训练家阵容每日都会重置",
    "The Battle Tower is an infinitely-scaling challenge in which every Pokemon defeated will increase the difficulty. Type Immunities inside this challenge will be instead converted to resistances": "对战塔是难度无限递增的挑战, 每击败一只宝可梦, 挑战难度便会提高。本挑战内的属性免疫效果将转换为属性抗性",
    "Your highest reached floor will be saved, and reset when the league rotation changes. You will be rewarded for every new highest floor reached at the end of the battle": "你抵达的最高层数将被记录, 联赛轮换时会进行重置。每次突破最高层数, 都将在对战结束后获得对应奖励",
    "Your highest reached score will be saved, and reset when the league rotation changes. You will be rewarded for your highest score reached at the end of the battle": "你取得的最高分数将被记录, 联赛轮换时会进行重置。你将在对战结束后, 根据取得的最高分数获得对应奖励",
    "The Battle Arena features five trainers in which you can select their difficulty for higher rewards. Field effects, battle modifiers, will also be randomised alongside the trainers. Trainers fought here will reset every day": "对战竞技场有 5 位训练家, 你可以选择他们的难度以获得更高的奖励。场地效果和战斗加成将和训练家一起随机生成。在这里对战的训练家每天都会重置",
    "There is a maximum of 100 Golden Bottlecaps achievable": "最多可获得100个金色王冠",
    //对战竞技场buff
    "Heavy Rain": "大雨",
    "Coarse Sandstorm": "猛烈沙暴",
    "Harsh Sun": "大日照",
    "Thick Fog": "浓雾",
    "Fierce Hail": "猛烈冰雹",
    "Grassy Field": "青草场地",
    "Electric Field": "电气场地",
    "Misty Field": "薄雾场地",
    "Permanent": "永久的",
    "All moves execute at the default speed (2s)": "所有招式以默认速度(2秒)执行",
    "All of your Pokemon gain": "你的所有宝可梦获得",
    "Iron Body": "钢铁之躯",
    "Super-effective damage on the enemy Pokemon is reduced to neutral": "对敌方宝可梦造成效果绝佳的伤害变为普通伤害",
    "Weakening Curse": "虚弱诅咒",
    "Physical damage dealt to the enemy is halved": "对敌方造成的物理伤害减半",
    "Fatiguing Curse": "疲劳诅咒",
    "Special damage dealt to the enemy is halved": "对敌方造成的特殊伤害减半",
    "Trick Field": "戏法场地",
    "Slower Pokemon become faster, faster Pokemon become slower": "速度较慢的宝可梦变得更快, 速度较快的宝可梦变得更慢",
    "Reverse Field": "反转场地",
    "Type weaknesses and strengths are reversed": "属性弱点与抗性反转",
    "Delta Stream": "德尔塔气流",
    "Weather changes are disabled": "天气不会改变",
    "Unnerve": "紧张感",
    "Items are disabled": "禁用道具",
    "No Mercy": "毫不留情",
    "Type-immune damage is now resisted instead of ignored": "原本属性免疫的伤害现在变为抵抗而非无效",
    "Wonder Ward": "神奇护盾",
    "Non super-effective damage dealt to the enemy is reduced by 80%": "对敌人造成的非效果绝佳伤害降低 80%",
    "Stealth Rocks": "隐形岩",
    "Switching Pokemon deal damage": "切换宝可梦时受到伤害",
    "Neutralising Gas": "化学气体",
    "Abilities are disabled": "禁用特性",
    "Serendipity": "意外之喜",
    "Your hit effects are twice as likely to happen": "追加效果触发几率翻倍",
    "Heavy Weather": "猛烈天气",
    "If an active team Pokemon typing does not match the current Weather, deal periodic damage": "如果出战宝可梦的属性与当前天气不匹配, 会定期受到伤害",
    //旅行
    //地图
    "Battle Summary": "战斗总结",
    "Save and Go!": "保存并出发！",
    "Fight Again": "再次战斗",
    "Level :": "等级 :",
    "Area Items": "区域物品",
    "Area Pokemon": "区域宝可梦",
    "Team Preview": "队伍预览",
    "Auto-Refight": "自动战斗",
    "Victory Rewards": "获胜奖励",
    //
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "All": "全部",
    "Classic": "经典",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Experience": "经验值",
    "Cancel": "取消",
    "Base Stats": "能力值和种族值",
    "Change or edit team": "更改或编辑队伍",
    "all": "全部",
    "Add Pokemon": "添加宝可梦",
    "[Coming Soon]": "[即将推出]",
    "Leave Combat": "离开战斗",
    "New Items!": "新物品!",
    "New Pokemon!": "新宝可梦!",
    "Fire / Water": "火 / 水",
    "Go play the official games!": "去玩官方游戏吧！",
    "All characters and related intellectual property featured are the exclusive property of Nintendo, Creatures Inc., and The Pokémon Company.": "所有的角色和相关的知识产权都是任天堂、Creatures Inc.和the poksammon Company的独家财产。",
    "Any use of assets is solely for non-commercial and entertainment purposes. No ownership is claimed, and all rights remain with their respective owners": "资产的任何使用仅用于非商业和娱乐目的。没有所有权要求, 所有权利仍属于各自的所有者",
    "IV's Stats": "个体值",
    "Learnt Moves": "学习招式",
    "Save and exit": "保存并退出",
    "Select a move below and replace it with one of the list of learnt moves": "选择下面的一个招式并将其替换为学习过的招式列表中的一个",
    "Select a starter!": "选择一个初始精灵！",
    "This project is entirely unofficial!": "这个项目是完全非官方的！",
    "Tip: Right click (or long-press on mobile) on most elements for additional information": "提示: 右键点击（或在手机上长按）大多数元素以获取额外信息",
    "Abort": "取消",
    "Operation finished!": "操作完成！",
    "Do you want to use a genetic-aiding item?": "你想使用一个遗传辅助物品吗？",
    "The item will be consumed on use": "物品将在使用时消耗",
    "Nope": "不要",
    "Obtained as a random reward in the Battle Frontier": "在 对战开拓区 作为随机奖励获得",
    "Complete the tutorial to access events": "完成教程以参与活动",


    "Select a Pokemon add to team": "请选择一只宝可梦加入队伍",
    "No new items or Pokemon :(": "暂无新物品或宝可梦 :(",
    "First team slot must not be empty!": "第一个队伍位置不能为空！",
    "Yeah!": "确定",
    "Are you sure you want to delete all data forever?": "你确定要永久删除所有数据吗？",
    "Check learnable moves": "查看可学习的招式",
    "New!": "新!",
    "DEF": "防御",
    "Iv's Up!": "个体值提高!",
    "No additional effects": "无额外效果",
    "Empty": "空",
    "Mystery Egg": "神秘的蛋",
    "An unhatched egg. Leave combat to discover the contents!": "一个未孵化的蛋。战斗结束后, 去发现其中的内容吧！",
    "Water / Dark": "水 / 恶",
    "Water / Electric": "水 / 电",
    "Water / Flying": "水 / 飞行",
    "Caught": "已捕捉",
    "Go Back": "返回",
    "✦Shiny✦!": "✦闪光✦!",
    "Moveset Tag Matches": "标签匹配的招式",
    "All-Type Moves": "其他可学习招式",
    "BP": "威力",
    "Close": "关闭",
    //缎带
    "Smile Ribbon": "微笑缎带",
    "Awarded very rarely for spending a lot of time together": "因共度漫长时光而极其罕见地获得",
    "Souvenir Ribbon": "纪念缎带",
    "Awarded in special occasions": "在特殊情况下授予",
    "Endurance Ribbon": "耐力缎带",
    "Awarded for reaching floor 30 in the Battle Tower": "在对战塔达到 30 层时获得",
    //百科
    "Inflicts Burn": "造成灼伤",
    "Inflicts Confused": "造成混乱",
    "Inflicts Paralysis": "造成麻痹",
    "Inflicts Poisoned": "造成中毒",
    "Same-Type: Fighting": "同属性: 格斗",
    "Same-Type: Bug": "同属性: 虫",
    "Same-Type: Dragon": "同属性: 龙",
    "Same-Type: Electric": "同属性: 电",
    "Same-Type: Fire": "同属性: 火",
    "Same-Type: Flying": "同属性: 飞行",
    "Same-Type: Ghost": "同属性: 幽灵",
    "Same-Type: Grass": "同属性: 草",
    "Same-Type: Ground": "同属性: 地面",
    "Same-Type: Normal": "同属性: 一般",
    "Same-Type: Poison": "同属性: 毒",
    "Same-Type: Psychic": "同属性: 超能力",
    "Same-Type: Rock": "同属性: 岩石",
    "Same-Type: Steel": "同属性: 钢",
    "Same-Type: Water": "同属性: 水",
    "Same-Type: Fairy": "同属性: 妖精",
    "Same-Type: Dark": "同属性: 恶",
    "not evolved": "未进化",
    "type": "属性",
    "level": "等级",
    "division": "评级",
    "is shiny": "闪光",
    //神秘礼物
    "Mystery Gift": "神秘礼物",
    "It will be shiny and carrying a Souvenir Ribbon": "它是闪光宝可梦, 还携带一个纪念缎带",
    //神兽介绍
    "Believed to be the result of an attempt to replicate the ancestor of all Pokémon. The experiment did not achieve its intended goal, and the creature that emerged was deemed a failure.": "据信是为了复现万灵始祖而进行实验的产物。实验未能达成其预定目标，诞生于此的存在亦被判定为失败之作。",
    "The cold of winter. Air chills and frost gathers in its wake. Snowfall follows as it passes, and mountains are left sealed in ice where it lingers.": "凛冬之寒。所经之处空气凝结，霜华渐聚。其行过时大雪纷至，驻足之地群山覆冰，冰封长驻。",
    "The storm of summer. Thunder rolls with its cry, and lightning strikes in time with its wings. The skies darken as it passes, and violent storms follow its soar.": "盛夏之雷暴。鸣响携雷声滚滚，振翅引电光灼灼。其翼展时天幕晦暗，翔掠之处暴风骤雨相随。",
    "The warmth of spring. Its fire does not scorch the world, but stirs it awake, melting snow and kindling new life. The cold loosens its hold as it passes, and the land is renewed by heat and light.": "阳春之温煦。其火不灼万物，反催苏生，融雪绽新。所过之处寒意消弭，大地因光热而万象更迭。",
    "Shaped by human hands, bears the weight of creation twisted. Though it carries the memory of life that came before, it walks a path apart, questioning the bounds of its own existence.": "由人类之手塑造，承载着扭曲创造的重量。虽铭刻着过往生灵的记忆，却踽踽独行于殊途，不断叩问自身存在的边界。",
    "The origin from which all Pokemon as we know trace their beginnings. Its form, small and gentle, carries the memory of every creature that would follow.": "我们所知一切宝可梦皆可追溯的起源。其形虽小而温顺，却承载着后世万千生灵的记忆。",
    "Traveling through time and appearing where the past and future meet, it preserves the natural order, ensuring that the cycles of life, growth, and seasons continue uninterrupted.": "穿越时空，现身于过去与未来的交汇之处。它维系着自然的秩序，确保生命、成长与季节的循环永续不辍。",
    "A reminder of the power that once carved the seas. Its ancient rivalry with Groudon lingers quietly, a balance written into the land and water.": "那股曾开凿海洋之伟力的残响。它与固拉多的古老争斗悄然延续，化作了大地与流水间书写的不变均衡。",
    "The oceans made visible, and the force that first shaped the seas across the world. Waves rise and storms gather at its will.": "海洋之形显化，亦是首度塑成寰宇间汪洋的伟力。波涛随其心意涌起，风暴亦应其意志汇集。",
    "A reminder of the power that once carved the lands. Its ancient rivalry with Kyogre lingers quietly, a balance written into the land and water.": "那股曾塑造大地之伟力的残响。它与盖欧卡的古老争斗悄然延续，化作了大地与流水间书写的不变均衡。",
    "The continents made whole, and the force that first shaped the land across the world. Mountains rise and deserts stretch at its will.": "大陆之形显化，亦是首度塑成世间万土的伟力。山峦随其心意隆起，荒漠亦应其意志延展。",
    "The force that watches over the world from above. It tempers the chaos of the seas and the land, acting as a mediator between Kyogre and Groudon. The winds and currents obey its passage, and it stands as guardian of the skies.": "自苍穹之上俯瞰并守护世界的伟力。它调和海洋与陆地的混沌，作为盖欧卡与固拉多之间的调停者。风云与洋流皆顺从它的轨迹，它即是守护苍穹的卫士。",
    "Ascending the atmosphere, its reach extending into the upper skies. Protecting not only the world below but the space above, guarding against threats from beyond.": "其存在升腾于大气，影响力直达高天之上。守护的不仅是下方的世界，还包括头顶的太空，抵御着来自天外的威胁。",
    "The embodiment of wishing, awakening only once in a thousand years. In those brief moments, it listens to the desires carried in the hearts of others, and its power brings those wishes into reality.": "愿望的化身，千年方得一度苏醒。在那短暂的时刻，它聆听着众生心中承载的渴望，并以自身之力令那些祈愿化为现实。",
    "Emerged to give shape to knowledge. When the world was still new, it shared understanding with humanity, allowing thought and memory to take root. Its presence quiets turmoil to the gods of time and space.": "为赋予知识以形态而诞生。当世界尚处新生，它将智慧分享予人类，让思想与记忆得以扎根。它的存在，能平息时空二神的纷乱。",
    "Emerged to give shape to emotion. When the world was still new, it shared feeling with humanity, allowing joy, sorrow, and empathy to take root. Its presence soothes unrest to the gods of time and space.": "为赋予情感以形态而诞生。当世界尚处新生，它将感受分享予人类，让喜悦、悲伤与共鸣得以扎根。它的存在，能抚慰时空二神的不安。",
    "Emerged to give shape to will. When the world was still new, it granted resolve to humanity, allowing action, choice, and determination to take form. Its presence steels the spirit of the gods of time and space.": "为赋予意志以形态而诞生。当世界尚处新生，它将决心授予人类，让行动、抉择与决断得以成形。它的存在，能为时空二神注入坚毅。",
    "Bound by weight and limit, a shape time itself can endure. Its power yet governs past and future, though restrained, for the world cannot withstand the full measure of eternity given form.": "被重力与限度所束缚，是时间本身所能承载的形态。其力量依然司掌过去与未来，但被加以制约，因这世界无法承受具象化的永恒之全部威能。",
    "Shaped by the Original One, when the universe had yet to know its first moment, It was brought forth to give law to duration. By its heartbeat, time began to flow; by its will, past and future were torn apart and given order. Without It, all life trapped by eternal stillness.": "由太初之物所塑，于宇宙尚未知晓其第一刻时被创造，为‘延续’订立法则。随其心跳，时间开始流动；凭其意志，过去与未来被撕裂并赋予秩序。若无它，一切生命都将困于永恒的静止。",
    "Bound by weight and limit, a shape space itself can sustain. Its power yet governs distance and separation, though restrained, for the world cannot bear the weight of infinite breadth given form.": "被重力与限度所束缚，是空间本身所能承载的形态。其力量依然司掌距离与分离，但被加以制约，因这世界无法承受具象化的无限宽广之全部重量。",
    "Shaped by the Original One, when the universe was yet unmeasured, It was brought forth to give form to expanse. By its existence, space became vast; by its will, distance gained meaning. Without It, the world would have no breadth, no separation between sky and land, nor any path for life to walk.": "由太初之物所塑，于宇宙尚不可度量时被创造，为‘广袤’赋予形态。因它的存在，空间变得辽阔；凭它的意志，距离有了意义。若无它，世界便无宽广，天与地将无分隔，生命亦无路可行。",
    "Formed within the depths of the earth, it moves through molten stone and scorched caverns, shaping volcanoes among the land through heat and pressure.": "诞生于地底深处，穿行于熔岩与焦灼的洞窟之中。它以热力与压力塑造大地上的火山。",
    "Regigigas moved the continents into place, hauling landmasses with ropes of stone and ice, shaping the world through sheer strength. From this labor came the order of the land, after which it fell into long slumber.": "雷吉奇卡斯曾拉动大陆，以石与冰的缆绳拖曳地壳，凭纯粹伟力塑造世界。陆地的秩序自此而生，而后它便陷入长眠。",
    "Bound by weight and limit, a shape reality can tolerate. Its power yet governs antimatter and opposition, though restrained, for the world cannot endure the force that unravels all creation made whole.": "被重力与限度所束缚，是现实本身所能容忍的形态。其力量依然司掌反物质与对立，但被加以制约，因这世界无法承受那足以令一切创造物分崩离析的力量。",
    "Shaped by the Original One, when the laws of creation first took form, It was born in defiance of them. Given dominion over antithesis of matter, It was cast away for its violence, bound to a world where logic collapses and direction has no meaning.": "由太初之物所塑，于创造之法则初显时诞生，却是为了与这些法则相悖而生。被赋予主宰物质对立面的权能，因其狂暴而被放逐，囚禁于逻辑崩塌、方向失却意义的破碎世界。",
    "The embodiment of moon light. From the earliest ages, it has watched over sleep and dreams, bringing peaceful rest where darkness gathers. Its feathers dispel the nightmares born by Darkrai, as they balance the quiet rhythm of night that was set into the world.": "月华之化身。自太初之时，便守护着睡眠与梦境，在黑暗汇聚处带来安宁的休憩。其翎羽能驱散由达克莱伊所生的梦魇，以此维系着铭刻于世间的、静谧的夜的韵律。",
    "The prince of the seas, the chosen of its kind, born with a bond that links all ocean life. It guides the creatures of the waters, preserving harmony beneath the waves.": "沧海之王子，其族裔中的天选者，生来便与所有海洋生灵存在着羁绊。它指引着水中的万千生命，维系着波涛之下的和谐。",
    "The embodiment of night shadow. From the earliest ages, it has been bound to dreams, drawing forth fear and unrest where its presence lingers. Nightmares follow in its wake, not by intent, but as a reflection of its nature.": "夜影之化身。自太初之时，便与梦境紧密相连，其所在之处，恐惧与不安随之滋生。梦魇随其踪迹而来，非其本意，实为其天性之映照。",
    "Embodying gratitude and the renewal of life, It moves across barren lands, leaving fields of flowers in its wake and restoring the vitality of nature, bringing growth and bloom to places long abandoned.": "象征着感恩与生命之复苏，它行经荒芜大地，所过之处花田绽放，令自然的生机重返，为久被遗弃之地带来生长与繁花。",
    "Embodying gratitude and the renewal of life, It moves across barren lands, leaving fields of flowers in its wake and restoring the vitality of nature, bringing growth and bloom to places long abandoned.": "象征着感恩与生命之复苏，它行经荒芜大地，所过之处花田绽放，令自然的生机重返，为久被遗弃之地带来生长与繁花。",
    "Emerging from nothing, existence was created from its birth. Pillars that govern reality shaped by its will, and yet, only a vessel for the eye to see, and the mind to comprehend.": "自虚无中诞生，存在因它的出生而被创造。统御现实的基石由其意志塑造，然而，这仅仅是为肉眼所见、为心智所能理解的容器。",
    //特性描述
    "When slotted as a non-hidden ability: Turns reduced to x2": "作为非隐藏特性时: 回合数 x2 ",
    "When slotted as a non-hidden ability: Damage reduced to x1.25": "作为非隐藏特性时: 伤害 x1.25",
    "When slotted as a non-hidden ability: Damage reduced to x1.5": "作为非隐藏特性时: 伤害 x1.5",
    "Positive stats up last x3 longer": "能力提高效果的持续回合 x3",
    "The user temporarily gets the (non-hidden) ability of the last defeated Pokemon on your team. This temporary ability works on top of your existing abilities. Applying a second temporary ability replaces the first one": "使用者暂时获得我方队伍中最后一只被打败的宝可梦的(非隐藏)特性。此临时特性与现有特性共存。施加第二个临时特性时, 将替换第一个",
    "Decreases fatigue damage of the user by x2": "疲劳伤害减半",
    "Decrease enemy Speed by 50% on getting hit": "受到攻击时, 使对手的速度降低 50%",
    "Super-effective damage becomes neutral": "效果绝佳的伤害变为普通伤害",
    "Status effects applied to the target last x3 longer": "对目标施加的异常状态效果持续回合 x3",
    "Multiply the damage dealt by x1.35 if the target has a status effect": "如果目标处于异常状态, 造成的伤害 x1.35",
    "Whenever anyone in the team gets a stat risen, the user will get it too": "每当队伍中任意宝可梦的能力提高时, 该宝可梦也会获得同样的提高",
    "Decreases the damage of all ghost moves by 25% (Can stack). Works always for everyone regardless of the user": "所有幽灵属性招式造成的伤害降低 25%（可叠加）。始终对全体有效, 与使用者无关",
    
    "(Heat Wave, Sandstorm, Gust, Tailwind, Hurricane, Icy Wind, Blizzard, Silver Wind, Leaf Storm, Ominous Wind, Fairy Wind, Magma Storm, Aeroblast, and Sandsear Storm)": "（热风、沙暴、起风、顺风、暴风、冰冻之风、暴风雪、银色旋风、飞叶风暴、奇异之风、妖精之风、熔岩风暴、气旋攻击、热沙风暴）",
    
    "Multiplies by x1.1 the damage of Ghost-type moves of all team members": "全队幽灵属性招式的伤害  x1.1",
    
    "Multiplies by x1.1 the power of Dark-type moves of all team members": "全队的恶属性招式伤害 x1.1",

    "All moves become Normal-type moves, and their power is multiplied by x1.2": "所有属性招式会变为一般属性, 且伤害 x1.2",

    "Changes the type of the user to match the type of the used move": "自身的属性变为所使用招式的对应属性",
    "Every turn, raises two stats by 100% for one turn": "每回合随机提高两项能力值 100%, 该效果持续 1 回合",
    "Increases the Attack by x1.2, but prevents them from switching": "攻击 x1.2, 但自身无法换下场",
    "Increases the highest stat of the user by 50% when defeating a Pokemon": "击败宝可梦后, 自身能力值最高的一项提高 50%",
    "Inverts stat changes. Positive changes become negative, and negative become positive": "反转自身的能力值变化效果",
    "Moves are executed a second time, at half power": "招式将额外触发 1 次, 次发招式的威力为原来的一半",
    "Physical damage dealt is multiplied by x2": "造成的物理伤害 x2 ",
    "Secondary effect of moves are executed twice": "招式的附加效果触发 2 次",
    "Stat changes on the user are boosted by a stage": "自身的能力值变化额外提高 1 级",
    "Moves that are resisted by typing do instead normal damage": "被属性抵抗的招式, 改为造成正常伤害",
    "Received damage from non-Super-Effective moves are reduced by 80%": "所受的非克制招式的伤害降低 80%",
    "Ghost and Dark-type moves are x1.5 faster than usual": "幽灵、恶属性招式的出招速度 x1.5 ",
    "Flying and Bug moves are x1.5 faster than usual": "飞行、虫属性招式的出招速度 x1.5 ",
    "Increases Speed by 50% when defeating a Pokemon": "击败宝可梦后, 自身速度提高 50%",
    

    "Copies the positive stat increases of the enemy": "复制对手的能力值正面提高效果",
    "Prevents all stat decreases": "能力值不会降低",
    "Increases the Damage dealt by x1.15 for every team member defeated": "每有一名队友被击败, 自身造成的伤害提高 15%",
    "Increase Attack by 100% when hit with a super-effective move": "受到属性克制招式攻击时, 攻击提高 100%",
    "Increase Special Attack by 100% when hit with a super-effective move": "受到属性克制招式攻击时, 特攻提高 100%",
    "Moves that execute faster than usual have their base power multiplied by x2": "速攻招式的招式威力 x2",
    "Moves that execute slower than usual have their base power multiplied by x1.5": "慢速招式的招式威力 x1.5",
    "Moves that hit multiple times always hit their maximum amount": "多段攻击招式必定打出最大攻击段数",
    "Nullifies received Electric-type moves and increases Speed by 50% after being hit with one": "免疫电属性招式, 且被该属性招式攻击后, 速度提高 50%",
    "Nullifies received Fairy-type moves and increases Speed by 50% after being hit with one": "免疫妖精属性招式, 且被该属性招式攻击后, 速度提高 50%",
    "Nullifies received Fire-type moves and increases Speed by 50% after being hit with one": "免疫火属性招式, 且被该属性招式攻击后, 速度提高 50%",
    "Nullifies received Ghost-type moves and increases Speed by 50% after being hit with one": "免疫幽灵属性招式, 且被该属性招式攻击后, 速度提高 50%",
    "Nullifies received Grass-type moves and increases Speed by 50% after being hit with one": "免疫草属性招式, 且被该属性招式攻击后, 速度提高 50%",
    "Nullifies received Ice-type moves and increases Speed by 50% after being hit with one": "免疫冰属性招式, 且被该属性招式攻击后, 速度提高 50%",
    "Nullifies received Poison-type moves and increases Speed by 50% after being hit with one": "免疫毒属性招式, 且被该属性招式攻击后, 速度提高 50%",
    "Nullifies received Psychic-type moves and increases Speed by 50% after being hit with one": "免疫超能力属性招式, 且被该属性招式攻击后, 速度提高 50%",
    "Nullifies received Water-type moves and increases Speed by 50% after being hit with one": "免疫水属性招式, 且被该属性招式攻击后, 速度提高 50%",
    "Super-effective damage taken multiplier is halved": "受到的属性克制伤害减半",
    
    

    
    
    
    "All hits become super-effective regardless of the typing": "所有攻击无视属性相性, 必定造成克制伤害",
    "Increases the chance of encountering a wild shiny pokemon by 15%. Works always for everyone regardless of the user": "野生闪光宝可梦的遭遇概率提高15%, 该效果对队伍中的所有宝可梦都生效, 与持有者无关",
    
    
    
    
    
    
    
    "Multiplies Same-Type-Attack-Bonus by x1.2": "本系加成再 x1.2",
    
    "Damage received is halved when over 50% HP": "自身生命高于 50% 时, 所受伤害减半",
    
    
    "This ability is currently unobtainable :(": "该特性目前无法获取 :(",
    //招式描述
    //技能描述
    "Attack becomes physical or special to match the highest stat of the user": "招式类型会变为物理或特殊, 以匹配使用者最高的攻击属性",
    "Bypasses all defense buffs": "无视所有防御能力变化",
    "Prevents the enemy to use the move in the slot embargo was used. This is treated as a status effect": "对手无法使用被查封的招式位上的招式。此效果被视为一种异常状态",
    "Decreases Attack by 50%": "攻击力降低 50%",
    "Split changes to match the highest stat of the user": "招式类型会与使用者最高的能力值一致",
    "all status effect": "所有状态效果",
    "Increases Attack by 150% but decreases Defense and Special Defense by 50%": "攻击提高 150%, 但防御与特防降低 50%",
    "and switches to the next party member": "并切换到队伍中下一只宝可梦",
    "Changes the type of the user corresponding to the": "改变使用者的属性根据不同的",
    "Increase all Stats by 50%": "所有能力值提高 50%",
    "Increases base power by 30 for every unique stat up of the user": "使用者每有一项能力值提高, 招式威力增加 30",
    "Increases Special Attack by 150%. Attacks x1.5 slower than usual": "特攻提高 150%。此招式出招速度比通常慢 1.5 倍",
    "Power increases by x1.2-1.5 if Speed is risen": "若速度提高, 招式威力 x1.2-1.5",
    "Increases Speed by 50% to the entire team": "整个队伍的速度提高 50%",
    "Increases Special Defense by 50% to the entire team": "整个队伍的特防提高 50%",
    "Power doubles if the user is Paralyzed, Burned or Poisoned": "如果使用者处于麻痹、灼伤或中毒状态, 则招式威力翻倍",
    "Power increases by x1.2-1.5 if Defense/Special Defense is risen": "如果防御或特防提高, 招式威力 x1.2~1.5",
    "Hits 2-5 times": "攻击 2-5 次",
    "Steals the stat changes of the enemy": "窃取对手的能力变化",
    "Switches to the next party member": "切换到队伍中的下一只宝可梦",
    "Power randomly varies from x1 to x8": "威力随机在 1-8 倍之间变化",
    "Power increases by x1.2-1.5 if Defense/Special Defense is risen": "如果防御或特防提高, 招式威力 x1.2~1.5",
    "Attacks x1.2 slower than usual. Power increases by x1.2-1.5 if Defense/Special Defense is risen": "此招式出招速度比通常慢 1.2 倍。如果防御或特防提高, 招式威力 x1.2~1.5",
    "Power doubles if the user is not holding any item": "如果使用者未携带任何物品, 则招式威力加倍",
    "Increases Speed by 50% to the entire team. Attacks x1.5 slower than usual": "全队速度提高 50%。此招式出招速度比通常慢 1.5 倍",
    "Decreases enemy Special Attack by 50%. Power increases by x1.2-1.5 if Defense/Special Defense is risen": "降低对手特攻 50%。如果防御或特防提高, 招式威力 x1.2~1.5",
    "Power doubles if the target has a status condition": "如果目标处于异常状态, 则招式威力加倍",
    "Faints the user and decreases enemy Attack and Special Attack by 100%": "使用者濒死, 并减少对手的攻击和特攻 100%",
    "Raises by 100% two random stats": "随机提高两个能力100%",
    "User transfers all of its stat changes and status to a the entire team": "使用者将其所有能力变化和状态转移给全队",
    "Increases Attack by 150% but decreases Defense and Special Defense by 100%": "攻击提高 150% 但防御和特防降低 100%",
    "Once used,increases the weight of rare item drops by 1% for the current battle. Multiple uses wont stack. Works always for everyone regardless of the user": "使用一次后, 当前战斗中稀有道具掉落的权重提高 1%, 多次使用不会叠加, 效果始终对队伍中所有人有效, 无论使用者是谁",
    "Once used,increases the weight of rare Pokemon by 1% for the current battle. Multiple uses wont stack. Works always for everyone regardless of the user": "使用一次后, 当前战斗中稀有宝可梦出现的权重提高 1%, 多次使用不会叠加, 效果始终对队伍中所有人有效, 无论使用者是谁",
    "User performs any move at random": "随机使用任何招式",
    "Perform the first move of the oponent, at double the base damage": "使用对手的第一个招式, 并使招式威力翻倍",
    "Perform the first move of the oponent. Attacks x2 faster than usual": "使用对手的第一个招式, 此招式出招速度比通常快 2 倍",
    "Super-effective against Water-types": "对水属性宝可梦效果绝佳",
    "Removes all status effect for the entire party": "移除全队所有异常状态",
    "Can hit regardless of the typing": "必定命中",
    //气象球
    "Power doubles under a weather condition, and type changes depending on it (": "在天气下威力加倍, 并且招式属性根据天气而改变（",
    "is Electric,": "电属性, ",
    "is Fire,": "火属性, ",
    "is Ghost,": "幽灵属性, ",
    "is Grass,": "草属性, ",
    "is Ground,": "地面属性, ",
    "is Ice,": "冰属性, ",
    "is Psychic )": "超能力属性）",
    "is Water,": "水属性, ",
    //
    "Changes the type of the user to the type of the first move slot": "将使用者的属性改变为第一个招式槽的属性",
    "Type changes based on the first type of the user": "招式属性根据使用者的第一个属性改变",
    "Executes the first move slot. Attacks x1.5 slower than usual": "执行第一个招式槽的招式。此招式出招速度比通常慢 1.5 倍",
    "Temporarily adds Fairy to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one": "暂时给对手添加妖精属性。临时属性的属性克制加成减半, 且施加第2个临时属性时会替换第1个",
    "Temporarily adds Ground to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one": "暂时给对手添加地面属性。临时属性的属性克制加成减半, 且施加第2个临时属性时会替换第1个",
    "Temporarily adds Electric to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one": "暂时给对手添加电属性。临时属性的属性克制加成减半, 且施加第2个临时属性时会替换第1个",
    "Temporarily adds Ghost to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one": "暂时给对手添加幽灵属性。临时属性的属性克制加成减半, 且施加第2个临时属性时会替换第1个",
    "Temporarily adds Grass to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one": "暂时给对手添加草属性。临时属性的属性克制加成减半, 且施加第2个临时属性时会替换第1个",
    "Temporarily adds Ground to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one": "暂时给对手添加地面属性。临时属性的属性克制加成减半, 且施加第2个临时属性时会替换第1个",
    "Temporarily adds Psychic to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one": "暂时给对手添加超能力属性。临时属性的属性克制加成减半, 且施加第2个临时属性时会替换第1个",
    "Temporarily adds Water to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one": "暂时给对手添加水属性。临时属性的属性克制加成减半, 且施加第2个临时属性时会替换第1个",
    //蛋招式

}


//需处理的前缀, 此处可以截取语句开头部分的内容进行汉化
//例如: Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头: "Coin: ":"金币: "
var cnPrefix = {
    "Use: Teach the ability": "使用时: 传授特性",
    "◇ Move inherited:": "◇ 招式遗传: ",
    "⟐ Egg Move inherited: ": "⟐ 蛋招式遗传: ",
    "Time left:":"剩余时间: ",

    "Long Press/Right click the present below to receive a gift": "长按/右击下方礼物, 即可获得礼物: ",

    "Current Type Rotation:": "当前轮换属性:",
    "Moves for ": "可学习的招式-",
    "This move is restricted (": "这个招式是受限的（",
    "Removes": "移除",
    "Damage Dealt": "造成的伤害",
    "Prevents all Pokemon on your team from": "防止我方队伍中的所有宝可梦遭受",
    //指南前缀
    "Battle: ": "战斗: ",
    "Genetics: ": "遗传学: ",
    "Caught: ": "已捕捉: ",
    "Remaining: ": "剩余: ",
    //训练
    "Difficulty: ": "难度: ",
    //活动地图提示
    "Requires an": "需要",
    "Requires a": "需要",
    "Requires x3": "需要 3个",
    
    "Increases the Damage dealt by x1.2 when afflicted with": "造成的伤害 x1.2, 且免疫该状态带来的持续伤害, 当陷入",
    "Increases Attack by 50% if afflicted with a status effect, and nullifies the stat redution of the condition": "如果处于异常状态, 攻击提高50%, 并免疫该状态带来的能力值降低",

    "Enemy damage over time from": "自身在场时, 对手受到",
    "Increases the highest stat of the user by 50% on": "自身能力值最高的一项提高 50%, 当处于",
    "Power doubles if the target is Paralyzed": "如果目标处于麻痹状态, 则威力加倍", //特殊排序
    "Power doubles if the target is Flying-Type": "如果目标是飞行属性, 则威力加倍", //特殊排序
    "Increases Attack and Speed by 50%. Attacks x1.4 slower than usual": "攻击和速度提高 50%。此招式出招速度比通常慢 1.4 倍",
    "Increases Special Attack and Speed by 50%. Attacks x1.4 slower than usual": "特攻和速度提高 50%。此招式出招速度比通常慢 1.4 倍",
    "Increases Attack and Speed by 50%": "攻击和速度提高 50%",
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑: ",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式: ",
    "In-line Exponent: ": "直列指数: ",
    "Single-Tab Mode: ": "单标签模式: ",
    "Time Played: ": "已玩时长: ",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示: ",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
}

//需处理的后缀, 此处可以截取语句结尾部分的内容进行汉化
//例如: 13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾: " Coin":" 金币"
var cnPostfix = {
    "⛔": "⛔",
    "is now level 100!": "到达 100 级!",
    "Halves the damage received of Ground-type moves": "受到地面属性招式的伤害减半",
    
    "the Pokemon Hidden Ability": "宝可梦的隐藏特性",
    "to enter": " 进入",
    "AFK time is being calculated, please wait...\n": "AFK 时间正在计算中, 请稍等...\n",
    "has been unlocked!": "已解锁!",
    //技能提示
    ") and only one of them can be present in the active moves at a time": "）在活跃招式中只能同时存在一个",
    "to the entire team": "给整个队伍",
    "and decreases enemy Speed by 50%": "并降低对手的速度 50%",
    "and increases Special Attack by 50%": "并使特攻提高 50%",
    "for the entire party": "给整个队伍",
    "on the user": "给使用者",
    
    ", but increases enemy Special Attack by 100%": ", 但会使对手的特攻提高100%",
    ", but increases Attack by 100%": ", 但使攻击力提高 100%",
    ", but increases enemy Attack by 100%": ", 但使对手的攻击力提高 100%",
    "is doubled while this Pokemon is active": "的持续伤害翻倍",
    ", and nullifies the damage overtime caused by it": "状态时",
    ", and nullifies the stat redution of the condition": "状态时",
    "x25": "x25",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n                        ": "\n                        ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " ▼": " ▼",
    " ▲": " ▲",
    " ▲▲": " ▲▲",
    " ▼▼": " ▼▼",
    "✔️": "✔️",
    " Tm": " Tm",
    //"Memory": "记忆",
}

//需排除的, 正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^\#([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.,]+)\-([\d\.,]+) ✈$/,
    /^([\d\.,]+)\-([\d\.,]+)  ✈$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    ///^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    ///^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    ///^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换, 带数字的固定格式句子
//纯数字: (\d+)
//字母加数字: ([\d\.]+[A-Za-z])
//逗号: ([\d\.,]+)
//带小数点的数字: ([\d\.]+)
//原样输出的字段: (.+)
//换行加空格: \n(.+)
//&nbsp;空格: \xA0
var cnRegReplace = new Map([
    [/\bHighest Spiraling Tower floor reached: (\d+)\b/, '达到的对战塔最高层数: $1 '],
    [/\bNext reward at (\d+) score\b/, '下一个奖励在 $1 分'],
    
    [/\bStock: (\d+)\b/, '库存: $1 '],
    
    [/^Average Time$/, '平均时间'],
    [/^Simple Aura$/, '朴素气场'],
    [/^Moody Aura$/, '变幻气场'],
    [/^Limited Area Until (\d+)\/(\d+)$/, '限制区域, 截止至$1月$2日'],
    [/^HP Remaining: (\d+)%$/, 'HP剩余: $1%'],
    [/^Reward: x(\d+)$/, '奖励: $1个'],
    [/^Trainer (\d+)\/5$/, '训练家: $1/5'],
    [/^Defeated: (\d+)\/5$/, '已击败: $1/5'],
    [/^Caught: (\d+)$/, '捕获数: $1'],
    
    //天气
    [/^Increases the damage of Fire-Type moves by (\d+)% and decreases the damage of Water-Type moves by (\d+)%$/, '火属性招式的伤害提高 $1%, 水属性招式的伤害降低 $2%'],
    [/^Increases the damage of Water-Type moves by (\d+)% and decreases the damage of Fire-Type moves by (\d+)%$/, '水属性招式的伤害提高 $1%, 火属性招式的伤害降低 $2%'],
    [/^Increases the damage of Grass and Bug-Type moves by (\d+)%$/, '草、虫属性招式的伤害提高 $1%'],
    [/^Increases the damage of Ice-Type moves by (\d+)%$/, '冰属性招式的伤害提高 $1%'],
    [/^Increases the damage of Rock and Ground-Type moves by (\d+)%$/, '岩石、地面属性招式的伤害提高 $1%'],
    [/^Increases the damage of Dark and Ghost-Type moves by (\d+)%$/, '恶、幽灵属性招式的伤害提高 $1%'],
    [/^Increases the damage of Electric and Steel-Type moves by (\d+)%$/, '电、钢属性招式的伤害提高 $1%'],
    [/^Increases the damage of Fairy and Psychic-Type moves by (\d+)%$/, '妖精、超能力属性招式的伤害提高 $1%'],
    [/^(\d+)% chance to inflict Burn$/, '有 $1% 的概率造成灼伤'],
    [/^(\d+)% chance to inflict Poisoned$/, '有 $1% 的概率造成中毒'],
    [/^(\d+)% chance to inflict Confused$/, '有 $1% 的概率造成混乱'],
    [/^(\d+)% chance to inflict Freeze$/, '有 $1% 的概率造成冰冻'],
    [/^(\d+)% chance to inflict Paralysis$/, '有 $1% 的概率造成麻痹'],
    [/^(\d+)% chance to inflict Sleep$/, '有 $1% 的概率造成睡眠'],
    [/^Multiplies base power by ([\d\.]+)x everytime its used, up to (\d+) times. Depletes all stacks upon switching Pokemon$/, '每次使用, 招式威力 x$1, 最多 $2 次。交换宝可梦时叠加效果消失'],
    [/^positive buffs used by 1 turn and increases damage dealt by x([\d\.]+)$/, '正面效果持续时间 1 回合, 并且造成的伤害 x$1'],
    [/^Decreases the duration of negative buffs received by 1 turn and decreases damage taken by x([\d\.]+)$/, '减少受到的负面效果持续 1 回合, 并且受到的伤害 ÷$1'],
    [/^Increases the Damage of the user by x([\d\.]+), but inflicts$/, '携带者的伤害 x$1, 但遭受'],
    [/^Increases the Attack of the user by x([\d\.]+), but prevents them from switching$/, '携带者的攻击 x$1, 但无法切换宝可梦'],
    [/^Increases the Special Attack of the user by x([\d\.]+), but prevents them from switching$/, '携带者的特攻 x$1, 但无法切换宝可梦'],
    [/^Increases the damage of the user by x([\d\.]+), but loses 1\/10 of its max HP per turn$/, '携带者的伤害 x$1, 但每回合损失最大生命值的1/10'],
    [/^Increase overall defense by x([\d\.]+), but the user cannot use moves with 0 power$/, '所有防御 x$1, 但使用者无法使用威力为0的招式'],
    [/^Decreases the duration of negative buffs received by (\d+) turns$/, '受到的负面效果持续时间减少 $1 回合'],
    [/^Increases damage dealt by x([\d\.]+), but once all the moves of the user are executed, switch to the previous team member$/, '造成的伤害 x$1, 但一旦携带者的所有招式执行完毕, 则切换到队伍中的上一只宝可梦'],
    [/^Increases damage dealt by x([\d\.]+), but once all the moves of the user are executed, switch to the next team member$/, '造成的伤害 x$1, 但一旦携带者的所有招式执行完毕, 则切换到队伍中的下一只宝可梦'],
    [/^Moves that attack faster than usual are executed x([\d\.]+) faster$/, '出招速度比通常更快的招式, 出招速度再 x$1'],
    [/^Multi-hit moves are guaranteed to hit \+(\d+) times and deal x1.2 more damage. Multi-hit moves cannot exceed their maximum hit count$/, '多次攻击招式保证额外多攻击 $1 次, 并且伤害 x1.2 。多次攻击招式无法超过其最大攻击次数'],
    [/^Moves that get more powerful the more stacks they have deal x([\d\.]+) more damage$/, '叠加次数越多威力越强的招式, 其伤害 x$1'],
    [/^Moves that have 0 power execute x([\d\.]+) faster$/, '威力为 0 的招式执行速度加快 $1 倍'],
    [/^Moves affected by Iron Fist deal x([\d\.]+) more damage, and their secondary effects are executed twice$/, '受铁拳影响的招式伤害 x$1, 且招式的追加效果会触发 2 次'],
    [/^Moves that attack slower than usual deal x([\d\.]+) more damage$/, '出招速度比通常更慢的招式,其伤害 x$1'],
    [/^Inceases damage dealt by x([\d\.]+) and increases Speed by 50% when hit by a Super-Effective move$/, '造成的伤害 x$1, 且受到效果绝佳招式攻击时速度提高 50%'],
    [/^Reduces fatigue damage of the user by x([\d\.]+)$/, '使用者的疲劳伤害减少 $1 倍'],
    [/^Increases the weight of rare item drops by (\d+)%. Works always for everyone regardless of the holder$/, '稀有道具掉落的权重增加 $1 %, 无论携带者是谁, 效果始终对整个队伍有效'],
    [/^Increases the weight of rare pokemon by (\d+)%. Works always for everyone regardless of the holder$/, '稀有宝可梦出现的权重增加 $1 %, 无论携带者是谁, 效果始终对整个队伍有效'],
    [/^Increases the experience gained by the pokemon by (\d+)%$/, '宝可梦获得的经验值增加 $1%'],
    [/^Increases the chance of encountering a wild shiny pokemon by (\d+)%. Works always for everyone regardless of the holder$/, '遇到野生闪光宝可梦的概率增加 $1%, 无论携带者是谁, 效果始终对整个队伍有效'],
    //神秘礼物
    [/^You have until January (\d+) to claim$/, '领取截止日期为 1 月 $1 日'],
    [/^You have until February (\d+) to claim$/, '领取截止日期为 2 月 $1 日'],
    [/^You have until March (\d+) to claim$/, '领取截止日期为 3 月 $1 日'],
    [/^You have until April (\d+) to claim$/, '领取截止日期为 4 月 $1 日'],
    [/^You have until May (\d+) to claim$/, '领取截止日期为 5 月 $1 日'],
    [/^You have until June (\d+) to claim$/, '领取截止日期为 6 月 $1 日'],
    [/^You have until July (\d+) to claim$/, '领取截止日期为 7 月 $1 日'],
    [/^You have until August (\d+) to claim$/, '领取截止日期为 8 月 $1 日'],
    [/^You have until September (\d+) to claim$/, '领取截止日期为 9 月 $1 日'],
    [/^You have until October (\d+) to claim$/, '领取截止日期为 10 月 $1 日'],
    [/^You have until November (\d+) to claim$/, '领取截止日期为 11 月 $1 日'],
    [/^You have until December (\d+) to claim$/, '领取截止日期为 12 月 $1 日'],
    //提高
    [/^Increases Defense by (\d+)%$/, '防御提高 $1%'],
    [/^Increases Special Defense by (\d+)%$/, '特防提高 $1%'],
    [/^Increases Speed by (\d+)%$/, '速度提高 $1%'],
    [/^Increases Attack by (\d+)%$/, '攻击提高 $1%'],
    
    [/^(\d+)% chance to increase all Stats by (\d+)%$/, '$1% 的概率使所有属性提高 $2%'],
    [/^(\d+)% chance to increase Special Attack by (\d+)%$/, '$1% 的概率使特攻提高 $2%'],
    [/^(\d+)% chance to increase Attack by (\d+)%$/, '$1% 的概率使攻击提高 $2%'],
    [/^(\d+)% chance to increase Speed by (\d+)%$/, '$1% 的概率使速度提高 $2%'],
    [/^(\d+)% chance to increase Defense by (\d+)%$/, '$1% 的概率使防御提高 $2%'],
    [/^(\d+)% chance to increase Special Defense by (\d+)%$/, '$1% 的概率使特防提高 $2%'],
    [/^(\d+)% chance to increase All Stats by (\d+)%$/, '$1% 的概率使所有属性提高 $2%'],
    [/^Increases Attack and Special Attack by (\d+)%$/, '攻击和特攻提高 $1%'],
    [/^Increases Attack and Defense by (\d+)%$/, '攻击和防御提高 $1%'],
    [/^Increases Attack by (\d+)% to the entire team$/, '全队攻击提高 $1%'],
    [/^Increases Attack by (\d+)% and Speed by (\d+)%$/, '攻击提高 $1%, 速度提高 $2%'],
    [/^Increases Special Defense and Special Attack by (\d+)%$/, '特防和特攻提高 $1%'],
    [/^Increases Special Defense by (\d+)% and Defense by (\d+)%$/, '特防提高 $1%, 防御提高 $2%'],
    [/^Increases Special Defense and Special Attack by (\d+)%, and Speed by (\d+)%$/, '特防和特攻提高 $1%, 速度提高 $2%'],
    [/^Increases Defense by (\d+)% and Special Defense by (\d+)%$/, '防御提高 $1%, 特防提高 $2%'],
    [/^Increases Special Attack by (\d+)% and Special Defense by (\d+)%$/, '特攻提高 $1%, 特防提高 $2%'],
    //降低
    [/^Decreases Special Attack by (\d+)%$/, '特攻降低 $1%'],
    [/^Decreases Speed by (\d+)%$/, '速度降低 $1%'],
    [/^Decreases Defense by (\d+)%$/, '防御降低 $1%'],
    [/^Decreases Defense and Special Defense by (\d+)%$/, '防御和特防降低 $1%'],
    [/^Decreases Defense and Attack by (\d+)%$/, '防御和攻击降低 $1%'],
    [/^Decreases Defense, Special Defense and Speed by (\d+)%$/, '防御、特防和速度降低 $1%'],
    [/^Decreases enemy Attack by (\d+)%$/, '使对手的攻击降低 $1%'],
    [/^Decreases enemy Special Attack by (\d+)%$/, '使对手的特攻降低 $1%'],
    [/^Decreases enemy Speed by (\d+)%$/, '使对手的速度降低 $1%'],
    [/^Decreases enemy Defense by (\d+)%$/, '使对手的防御降低 $1%'],
    [/^Decreases enemy Special Defense by (\d+)%$/, '使对手的特防降低 $1%'],
    [/^Decreases enemy Attack by (\d+)% and Special Attack by (\d+)%$/, '使对手的攻击降低 $1%, 特攻降低 $2%'],
    [/^(\d+)% chance to decrease enemy Attack by (\d+)%$/, '$1% 的概率使对手的攻击降低 $2%'],
    [/^(\d+)% chance to decrease enemy Special Attack by (\d+)%$/, '$1% 的概率使对手的特攻降低 $2%'],
    [/^(\d+)% chance to decrease enemy Speed by (\d+)%$/, '$1% 的概率使对手的速度降低 $2%'],
    [/^(\d+)% chance to decrease enemy Defense by (\d+)%$/, '$1% 的概率使对手的防御降低 $2%'],
    [/^(\d+)% chance to decrease enemy Special Defense by (\d+)%$/, '$1% 的概率使对手的特防降低 $2%'],
    
    [/^Highest Reached Floor: (\d+)$/, '最高抵达层数: $1'],
    [/^Highest Score: (\d+)$/, '最高分数: $1'],
    [/^Score: (\d+)$/, '分数: $1'],
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Rotation (.+) \(ends in$/, '转 $1 (距离结束'],
    [/^Attacks x([\d\.]+) faster than usual$/, '此招式出招速度比通常快 $1 倍'],
    [/^Attacks x([\d\.]+) slower than usual$/, '此招式出招速度比通常慢 $1 倍'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 妖精'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 妖精'],
    [/^Hits (\d+) times$/, '攻击 $1 次'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 妖精'],
    [/^([\d\.,]+) Remaining$/, '$1 剩余'],
    [/^Normal, ([\d\.]+) Power, Physical$/, '一般, $1 BP, 物理'],
    [/^Normal, ([\d\.]+) Power, Special$/, '一般, $1 BP, 特殊'],
    [/^Fire, ([\d\.]+) Power, Physical$/, '火, $1 BP, 物理'],
    [/^Fire, ([\d\.]+) Power, Special$/, '火, $1 BP, 特殊'],
    [/^Water, ([\d\.]+) Power, Physical$/, '水, $1 BP, 物理'],
    [/^Water, ([\d\.]+) Power, Special$/, '水, $1 BP, 特殊'],
    [/^Electric, ([\d\.]+) Power, Physical$/, '电, $1 BP, 物理'],
    [/^Electric, ([\d\.]+) Power, Special$/, '电, $1 BP, 特殊'],
    [/^Grass, ([\d\.]+) Power, Physical$/, '草, $1 BP, 物理'],
    [/^Grass, ([\d\.]+) Power, Special$/, '草, $1 BP, 特殊'],
    [/^Ice, ([\d\.]+) Power, Physical$/, '冰, $1 BP, 物理'],
    [/^Ice, ([\d\.]+) Power, Special$/, '冰, $1 BP, 特殊'],
    [/^Fighting, ([\d\.]+) Power, Physical$/, '格斗, $1 BP, 物理'],
    [/^Fighting, ([\d\.]+) Power, Special$/, '格斗, $1 BP, 特殊'],
    [/^Poison, ([\d\.]+) Power, Physical$/, '毒, $1 BP, 物理'],
    [/^Poison, ([\d\.]+) Power, Special$/, '毒, $1 BP, 特殊'],
    [/^Ground, ([\d\.]+) Power, Physical$/, '地面, $1 BP, 物理'],
    [/^Ground, ([\d\.]+) Power, Special$/, '地面, $1 BP, 特殊'],
    [/^Flying, ([\d\.]+) Power, Physical$/, '飞行, $1 BP, 物理'],
    [/^Flying, ([\d\.]+) Power, Special$/, '飞行, $1 BP, 特殊'],
    [/^Psychic, ([\d\.]+) Power, Physical$/, '超能力, $1 BP, 物理'],
    [/^Psychic, ([\d\.]+) Power, Special$/, '超能力, $1 BP, 特殊'],
    [/^Bug, ([\d\.]+) Power, Physical$/, '虫, $1 BP, 物理'],
    [/^Bug, ([\d\.]+) Power, Special$/, '虫, $1 BP, 特殊'],
    [/^Rock, ([\d\.]+) Power, Physical$/, '岩石, $1 BP, 物理'],
    [/^Rock, ([\d\.]+) Power, Special$/, '岩石, $1 BP, 特殊'],
    [/^Ghost, ([\d\.]+) Power, Physical$/, '幽灵, $1 BP, 物理'],
    [/^Ghost, ([\d\.]+) Power, Special$/, '幽灵, $1 BP, 特殊'],
    [/^Dark, ([\d\.]+) Power, Physical$/, '恶, $1 BP, 物理'],
    [/^Dark, ([\d\.]+) Power, Special$/, '恶, $1 BP, 特殊'],
    [/^Dragon, ([\d\.]+) Power, Physical$/, '龙, $1 BP, 物理'],
    [/^Dragon, ([\d\.]+) Power, Special$/, '龙, $1 BP, 特殊'],
    [/^Steel, ([\d\.]+) Power, Physical$/, '钢, $1 BP, 物理'],
    [/^Steel, ([\d\.]+) Power, Special$/, '钢, $1 BP, 特殊'],
    [/^Fairy, ([\d\.]+) Power, Physical$/, '妖精, $1 BP, 物理'],
    [/^Fairy, ([\d\.]+) Power, Special$/, '妖精, $1 BP, 特殊'],
    [/^\(([\d\.,]+) BP, Spe\)$/, '($1 BP, 特殊)'],
    [/^\(([\d\.,]+) BP, Special\)$/, '($1 BP, 特殊)'],
    [/^\(([\d\.,]+) BP, Phy\)$/, '($1 BP, 物理)'],
    [/^\(([\d\.,]+) BP, Physical\)$/, '($1 BP, 物理)'],
    [/^([\d\.,]+) in total \(([\d\.,]+) left for next level\)$/, '$1 总计 (下一级还差 $2)'],
    [/^([\d\.,]+) in total \(max level reached\)$/, '$1 总计 (已满级)'],
    [/^([\d\.,]+) Power, Physical$/, '$1 威力, 物理'],
    [/^([\d\.,]+) Power, Special$/, '$1 威力, 特殊'],
    [/^Tier (.+) Raid ❖$/,'阶级 $1 团体战 ❖'],
    [/^Trainer Level ([\d\.,]+)$/, '训练师等级 $1'],
    [/^lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Level: ([\d\.,]+)$/, '等级: $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Team ([\d\.,]+)$/, '队伍 $1'],
    [/^Highest Floor: ([\d\.,]+)$/, '最高层数: $1'],
    [/^Floor: ([\d\.,]+)$/, '层数: $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^Level: ([\d\.,]+)\-([\d\.,]+)$/, '等级: $1\-$2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级: $1 \/ $2'],
    [/^Rotation ([\d\.,]+)\/([\d\.,]+)$/, '轮次 $1 \/ $2'],
]);